### ISSUE TITLE
Play 3D Amstrad games and analyze them

### ISSUE THREAD

**Issue by donluispanis** [wasted-horchata/cpcretrodev2019#2]
* Search them mostly drawn in Wireframe
* Look after reference games
* See what artistic styles do they have
* See what mechanics do they use
* Analyse and choose graphic mode

**Comment by Alexei-117** [comment]
* Wolfenstein in 3D for amstrad: https://www.youtube.com/watch?v=FKPiBPNG1OI
* * Source code: https://cpcrulez.fr/GamesTest/wolf_3d_preview.htm
* Combination of 2D and "Fake" 3D, "3D Stunt Rider": https://www.youtube.com/watch?v=XtCIjbD56os
